runtime: go
api_version: go1
application: unifiednotify
version: 1

handlers:
  - url: /(auth|authgoogle|googleoauthcallback|donegoogleauth)$
    script: _go_app
  - url: /(.*\.(css|js|jpg|png))$
    static_files: client/\1
    upload: client/.*\.(css|js|jpg|png)$
  - url: /.*
    static_files: client/index.html
    upload: client/index.html
